version: 2.1

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers
    steps:
    - checkout

    - run:
        name: Install dependencies
        command: npm install

    - run:
        name: Lint codebase
        command: npm run lint:js

    - run:
        name: Run tests
        command: npm run test

    - run:
        name: Run build
        command: npm run build

orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@1.2.5

